import { Component, NgModule } from '@angular/core';
import {MatInputModule} from '@angular/material/input';
import {MatFormFieldModule} from '@angular/material/form-field';
import {MatButtonModule} from '@angular/material/button';
import { FormsModule, NgForm } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { Console } from 'console';

@Component({
  selector: 'app-template-driven-form',
  standalone: true,
  imports: [MatInputModule,MatFormFieldModule,MatButtonModule,FormsModule,CommonModule],
  templateUrl: './template-driven-form.component.html',
  styleUrl: './template-driven-form.component.css',
})

export class TemplateDrivenFormComponent {

isFormSubmitted: boolean =false;

// Store all variables of every form field used inside form tag
  userObj:any = {
    firstName:'',
    lastName:'',
    userName:'',
    gender:'',
    phone: '',
    phoneNum:'',
    cnic:'',
    city:'',
    country:'',
    file:'',
    isAgree: false,
  }

  countries = [
    { name: 'Afghanistan', code: 'AF', numcode: '(+93)' },
    { name: 'Albania', code: 'AL', numcode: '(+355)' },
    { name: 'Algeria', code: 'DZ', numcode: '(+213)' },
    { name: 'Andorra', code: 'AD', numcode: '(+376)' },
    { name: 'Angola', code: 'AO', numcode: '(+244)' },
    { name: 'Antigua and Barbuda', code: 'AG', numcode: '(+1-268)' },
    { name: 'Argentina', code: 'AR', numcode: '(+54)' },
    { name: 'Armenia', code: 'AM', numcode: '(+374)' },
    { name: 'Australia', code: 'AU', numcode: '(+61)' },
    { name: 'Austria', code: 'AT', numcode: '(+43)' },
    { name: 'Azerbaijan', code: 'AZ', numcode: '(+994)' },
    { name: 'Bahamas', code: 'BS', numcode: '(+1-242)' },
    { name: 'Bahrain', code: 'BH', numcode: '(+973)' },
    { name: 'Bangladesh', code: 'BD', numcode: '(+880)' },
    { name: 'Barbados', code: 'BB', numcode: '(+1-246)' },
    { name: 'Belarus', code: 'BY', numcode: '(+375)' },
    { name: 'Belgium', code: 'BE', numcode: '(+32)' },
    { name: 'Belize', code: 'BZ', numcode: '(+501)' },
    { name: 'Benin', code: 'BJ', numcode: '(+229)' },
    { name: 'Bhutan', code: 'BT', numcode: '(+975)' },
    { name: 'Bolivia', code: 'BO', numcode: '(+591)' },
    { name: 'Bosnia and Herzegovina', code: 'BA', numcode: '(+387)' },
    { name: 'Botswana', code: 'BW', numcode: '(+267)' },
    { name: 'Brazil', code: 'BR', numcode: '(+55)' },
    { name: 'Brunei', code: 'BN', numcode: '(+673)' },
    { name: 'Bulgaria', code: 'BG', numcode: '(+359)' },
    { name: 'Burkina Faso', code: 'BF', numcode: '(+226)' },
    { name: 'Burundi', code: 'BI', numcode: '(+257)' },
    { name: 'Cabo Verde', code: 'CV', numcode: '(+238)' },
    { name: 'Cambodia', code: 'KH', numcode: '(+855)' },
    { name: 'Cameroon', code: 'CM', numcode: '(+237)' },
    { name: 'Canada', code: 'CA', numcode: '(+1)' },
    { name: 'Central African Republic', code: 'CF', numcode: '(+236)' },
    { name: 'Chad', code: 'TD', numcode: '(+235)' },
    { name: 'Chile', code: 'CL', numcode: '(+56)' },
    { name: 'China', code: 'CN', numcode: '(+86)' },
    { name: 'Colombia', code: 'CO', numcode: '(+57)' },
    { name: 'Comoros', code: 'KM', numcode: '(+269)' },
    { name: 'Congo (Congo-Brazzaville)', code: 'CG', numcode: '(+242)' },
    { name: 'Costa Rica', code: 'CR', numcode: '(+506)' },
    { name: 'Croatia', code: 'HR', numcode: '(+385)' },
    { name: 'Cuba', code: 'CU', numcode: '(+53)' },
    { name: 'Cyprus', code: 'CY', numcode: '(+357)' },
    { name: 'Czech Republic', code: 'CZ', numcode: '(+420)' },
    { name: 'Democratic Republic of the Congo', code: 'CD', numcode: '(+243)' },
    { name: 'Denmark', code: 'DK', numcode: '(+45)' },
    { name: 'Djibouti', code: 'DJ', numcode: '(+253)' },
    { name: 'Dominica', code: 'DM', numcode: '(+1-767)' },
    { name: 'Dominican Republic', code: 'DO', numcode: '(+1-809)' },
    { name: 'East Timor (Timor-Leste)', code: 'TL', numcode: '(+670)' },
    { name: 'Ecuador', code: 'EC', numcode: '(+593)' },
    { name: 'Egypt', code: 'EG', numcode: '(+20)' },
    { name: 'El Salvador', code: 'SV', numcode: '(+503)' },
    { name: 'Equatorial Guinea', code: 'GQ', numcode: '(+240)' },
    { name: 'Eritrea', code: 'ER', numcode: '(+291)' },
    { name: 'Estonia', code: 'EE', numcode: '(+372)' },
    { name: 'Eswatini (fmr. "Swaziland")', code: 'SZ', numcode: '(+268)' },
    { name: 'Ethiopia', code: 'ET', numcode: '(+251)' },
    { name: 'Fiji', code: 'FJ', numcode: '(+679)' },
    { name: 'Finland', code: 'FI', numcode: '(+358)' },
    { name: 'France', code: 'FR', numcode: '(+33)' },
    { name: 'Gabon', code: 'GA', numcode: '(+241)' },
    { name: 'Gambia', code: 'GM', numcode: '(+220)' },
    { name: 'Georgia', code: 'GE', numcode: '(+995)' },
    { name: 'Germany', code: 'DE', numcode: '(+49)' },
    { name: 'Ghana', code: 'GH', numcode: '(+233)' },
    { name: 'Greece', code: 'GR', numcode: '(+30)' },
    { name: 'Grenada', code: 'GD', numcode: '(+1-473)' },
    { name: 'Guatemala', code: 'GT', numcode: '(+502)' },
    { name: 'Guinea', code: 'GN', numcode: '(+224)' },
    { name: 'Guinea-Bissau', code: 'GW', numcode: '(+245)' },
    { name: 'Guyana', code: 'GY', numcode: '(+592)' },
    { name: 'Haiti', code: 'HT', numcode: '(+509)' },
    { name: 'Honduras', code: 'HN', numcode: '(+504)' },
    { name: 'Hungary', code: 'HU', numcode: '(+36)' },
    { name: 'Iceland', code: 'IS', numcode: '(+354)' },
    { name: 'India', code: 'IN', numcode: '(+91)' },
    { name: 'Indonesia', code: 'ID', numcode: '(+62)' },
    { name: 'Iran', code: 'IR', numcode: '(+98)' },
    { name: 'Iraq', code: 'IQ', numcode: '(+964)' },
    { name: 'Ireland', code: 'IE', numcode: '(+353)' },
    { name: 'Israel', code: 'IL', numcode: '(+972)' },
    { name: 'Italy', code: 'IT', numcode: '(+39)' },
    { name: 'Ivory Coast', code: 'CI', numcode: '(+225)' },
    { name: 'Jamaica', code: 'JM', numcode: '(+1-876)' },
    { name: 'Japan', code: 'JP', numcode: '(+81)' },
    { name: 'Jordan', code: 'JO', numcode: '(+962)' },
    { name: 'Kazakhstan', code: 'KZ', numcode: '(+7)' },
    { name: 'Kenya', code: 'KE', numcode: '(+254)' },
    { name: 'Kiribati', code: 'KI', numcode: '(+686)' },
    { name: 'Kosovo', code: 'XK', numcode: '(+383)' },
    { name: 'Kuwait', code: 'KW', numcode: '(+965)' },
    { name: 'Kyrgyzstan', code: 'KG', numcode: '(+996)' },
    { name: 'Laos', code: 'LA', numcode: '(+856)' },
    { name: 'Latvia', code: 'LV', numcode: '(+371)' },
    { name: 'Lebanon', code: 'LB', numcode: '(+961)' },
    { name: 'Lesotho', code: 'LS', numcode: '(+266)' },
    { name: 'Liberia', code: 'LR', numcode: '(+231)' },
    { name: 'Libya', code: 'LY', numcode: '(+218)' },
    { name: 'Liechtenstein', code: 'LI', numcode: '(+423)' },
    { name: 'Lithuania', code: 'LT', numcode: '(+370)' },
    { name: 'Luxembourg', code: 'LU', numcode: '(+352)' },
    { name: 'Madagascar', code: 'MG', numcode: '(+261)' },
    { name: 'Malawi', code: 'MW', numcode: '(+265)' },
    { name: 'Malaysia', code: 'MY', numcode: '(+60)' },
    { name: 'Maldives', code: 'MV', numcode: '(+960)' },
    { name: 'Mali', code: 'ML', numcode: '(+223)' },
    { name: 'Malta', code: 'MT', numcode: '(+356)' },
    { name: 'Marshall Islands', code: 'MH', numcode: '(+692)' },
    { name: 'Mauritania', code: 'MR', numcode: '(+222)' },
    { name: 'Mauritius', code: 'MU', numcode: '(+230)' },
    { name: 'Mexico', code: 'MX', numcode: '(+52)' },
    { name: 'Micronesia', code: 'FM', numcode: '(+691)' },
    { name: 'Moldova', code: 'MD', numcode: '(+373)' },
    { name: 'Monaco', code: 'MC', numcode: '(+377)' },
    { name: 'Mongolia', code: 'MN', numcode: '(+976)' },
    { name: 'Montenegro', code: 'ME', numcode: '(+382)' },
    { name: 'Morocco', code: 'MA', numcode: '(+212)' },
    { name: 'Mozambique', code: 'MZ', numcode: '(+258)' },
    { name: 'Myanmar (formerly Burma)', code: 'MM', numcode: '(+95)' },
    { name: 'Namibia', code: 'NA', numcode: '(+264)' },
    { name: 'Nauru', code: 'NR', numcode: '(+674)' },
    { name: 'Nepal', code: 'NP', numcode: '(+977)' },
    { name: 'Netherlands', code: 'NL', numcode: '(+31)' },
    { name: 'New Zealand', code: 'NZ', numcode: '(+64)' },
    { name: 'Nicaragua', code: 'NI', numcode: '(+505)' },
    { name: 'Niger', code: 'NE', numcode: '(+227)' },
    { name: 'Nigeria', code: 'NG', numcode: '(+234)' },
    { name: 'North Korea', code: 'KP', numcode: '(+850)' },
    { name: 'North Macedonia (formerly Macedonia)', code: 'MK', numcode: '(+389)' },
    { name: 'Norway', code: 'NO', numcode: '(+47)' },
    { name: 'Oman', code: 'OM', numcode: '(+968)' },
    { name: 'Pakistan', code: 'PK', numcode: '(+92)' },
    { name: 'Palau', code: 'PW', numcode: '(+680)' },
    { name: 'Palestine State', code: 'PS', numcode: '(+970)' },
    { name: 'Panama', code: 'PA', numcode: '(+507)' },
    { name: 'Papua New Guinea', code: 'PG', numcode: '(+675)' },
    { name: 'Paraguay', code: 'PY', numcode: '(+595)' },
    { name: 'Peru', code: 'PE', numcode: '(+51)' },
    { name: 'Philippines', code: 'PH', numcode: '(+63)' },
    { name: 'Poland', code: 'PL', numcode: '(+48)' },
    { name: 'Portugal', code: 'PT', numcode: '(+351)' },
    { name: 'Qatar', code: 'QA', numcode: '(+974)' },
    { name: 'Romania', code: 'RO', numcode: '(+40)' },
    { name: 'Russia', code: 'RU', numcode: '(+7)' },
    { name: 'Rwanda', code: 'RW', numcode: '(+250)' },
    { name: 'Saint Kitts and Nevis', code: 'KN', numcode: '(+1-869)' },
    { name: 'Saint Lucia', code: 'LC', numcode: '(+1-758)' },
    { name: 'Saint Vincent and the Grenadines', code: 'VC', numcode: '(+1-784)' },
    { name: 'Samoa', code: 'WS', numcode: '(+685)' },
    { name: 'San Marino', code: 'SM', numcode: '(+378)' },
    { name: 'Sao Tome and Principe', code: 'ST', numcode: '(+239)' },
    { name: 'Saudi Arabia', code: 'SA', numcode: '(+966)' },
    { name: 'Senegal', code: 'SN', numcode: '(+221)' },
    { name: 'Serbia', code: 'RS', numcode: '(+381)' },
    { name: 'Seychelles', code: 'SC', numcode: '(+248)' },
    { name: 'Sierra Leone', code: 'SL', numcode: '(+232)' },
    { name: 'Singapore', code: 'SG', numcode: '(+65)' },
    { name: 'Slovakia', code: 'SK', numcode: '(+421)' },
    { name: 'Slovenia', code: 'SI', numcode: '(+386)' },
    { name: 'Solomon Islands', code: 'SB', numcode: '(+677)' },
    { name: 'Somalia', code: 'SO', numcode: '(+252)' },
    { name: 'South Africa', code: 'ZA', numcode: '(+27)' },
    { name: 'South Korea', code: 'KR', numcode: '(+82)' },
    { name: 'South Sudan', code: 'SS', numcode: '(+211)' },
    { name: 'Spain', code: 'ES', numcode: '(+34)' },
    { name: 'Sri Lanka', code: 'LK', numcode: '(+94)' },
    { name: 'Sudan', code: 'SD', numcode: '(+249)' },
    { name: 'Suriname', code: 'SR', numcode: '(+597)' },
    { name: 'Sweden', code: 'SE', numcode: '(+46)' },
    { name: 'Switzerland', code: 'CH', numcode: '(+41)' },
    { name: 'Syria', code: 'SY', numcode: '(+963)' },
    { name: 'Taiwan', code: 'TW', numcode: '(+886)' },
    { name: 'Tajikistan', code: 'TJ', numcode: '(+992)' },
    { name: 'Tanzania', code: 'TZ', numcode: '(+255)' },
    { name: 'Thailand', code: 'TH', numcode: '(+66)' },
    { name: 'Togo', code: 'TG', numcode: '(+228)' },
    { name: 'Tonga', code: 'TO', numcode: '(+676)' },
    { name: 'Trinidad and Tobago', code: 'TT', numcode: '(+1-868)' },
    { name: 'Tunisia', code: 'TN', numcode: '(+216)' },
    { name: 'Turkey', code: 'TR', numcode: '(+90)' },
    { name: 'Turkmenistan', code: 'TM', numcode: '(+993)' },
    { name: 'Tuvalu', code: 'TV', numcode: '(+688)' },
    { name: 'Uganda', code: 'UG', numcode: '(+256)' },
    { name: 'Ukraine', code: 'UA', numcode: '(+380)' },
    { name: 'United Arab Emirates', code: 'AE', numcode: '(+971)' },
    { name: 'United Kingdom', code: 'GB', numcode: '(+44)' },
    { name: 'United States', code: 'US', numcode: '(+1)' },
    { name: 'Uruguay', code: 'UY', numcode: '(+598)' },
    { name: 'Uzbekistan', code: 'UZ', numcode: '(+998)' },
    { name: 'Vanuatu', code: 'VU', numcode: '(+678)' },
    { name: 'Vatican City', code: 'VA', numcode: '(+379)' },
    { name: 'Venezuela', code: 'VE', numcode: '(+58)' },
    { name: 'Vietnam', code: 'VN', numcode: '(+84)' },
    { name: 'Yemen', code: 'YE', numcode: '(+967)' },
    { name: 'Zambia', code: 'ZM', numcode: '(+260)' },
    { name: 'Zimbabwe', code: 'ZW', numcode: '(+263)' }
  ];
  

  // For phone Number
  phoneNumber: string = '';

  formatPhoneNumber(): void {
    const countryCodeSelect = document.getElementById('countryCode') as HTMLSelectElement;
    const phoneNumberInput = document.getElementById('phoneNumber') as HTMLInputElement;

    const countryCode = countryCodeSelect.value;
    let phoneNumber = phoneNumberInput.value.replace(/\D/g, '');

    if (!phoneNumber.startsWith(countryCode)) {
      phoneNumber = countryCode + phoneNumber;
    }

    this.phoneNumber = phoneNumber;
  }
// Once user clicked on submit form 
  OnSubmit(form:NgForm){
    const isFormValid=form.form.valid;
this.isFormSubmitted=true;
console.log( alert('Form Submitted'));
  }




}
